# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: snapetech.iptvtunerr
PackageVersion: 0.1.72
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: iptv-tunerr-v0.1.72-windows-amd64.exe
  PortableCommandAlias: iptv-tunerr
Commands:
- iptv-tunerr
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/snapetech/iptvtunerr/releases/download/v0.1.72/iptv-tunerr-v0.1.72-windows-amd64.zip
  InstallerSha256: 608c51f15e258eea803e129bbf3de72ee9dc64674aef161231f7fc8da5217a84
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-05-13
